---
- name: Install docker
  become: yes
  become_user: root
  dnf:
    name: docker
    state: latest

- name: Run and enable docker
  become: yes
  become_user: root
  service:
    name: docker
    state: started
    enabled: true

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Create docker group
  become: yes
  become_user: root
  group:
    name: docker
    state: present

- name: Add a current user to docker group
  become: yes
  become_user: root
  user:
    name: '{{ ansible_user_id }}'
    groups: docker
    append: yes

- name: Change docker directory ownership and permissions
  file:
    dest: '/home/{{ ansible_user_id }}/.docker'
    owner: '{{ ansible_user_id }}'
    mode: g+rwx
    recurse: yes
