---
- name: Install required system packages
  become: yes
  become_user: root
  apt:
    name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
        - gnupg-agent
    state: latest
    update_cache: no

- include_tasks: ../common/install-package-from-third-party.yml
  vars:
    package: docker-ce
    gpg_key_name: docker-keyring.asc
    arch: amd64

- name: Run and enable docker
  become: yes
  become_user: root
  service:
    name: docker
    state: started
    enabled: true

- name: Create docker group
  become: yes
  become_user: root
  group:
    name: docker
    state: present

- name: Add a current user to docker group
  become: yes
  become_user: root
  user:
    name: '{{ ansible_user_id }}'
    groups: docker
    append: yes

- name: Change docker directory ownership and permissions
  file:
    dest: '/home/{{ ansible_user_id }}/.docker'
    owner: '{{ ansible_user_id }}'
    mode: g+rwx
    recurse: yes

- name: Active the changes to groups
  shell: newgrp docker
