---
- name: playbook to install arandr
  hosts: localhost
  connection: local

  tasks:
    - name: Install arandr
      become: true
      apt:
        name: arandr
        state: latest
        update_cache: no
