---
- name: playbook to install atom
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/atom.yml

  tasks:
    - name: install dependencies
      become: yes
      apt:
        name:
          - apt-transport-https
          - gnupg2
        state: latest

    - name: Create symlink to use python3
      become: yes
      file:
        src: /usr/bin/python3
        dest: /usr/bin/python
        state: link

    - include_tasks: ../common/install-package-from-third-party.yml
      vars:
        gpg_key: https://packagecloud.io/AtomEditor/atom/gpgkey
        repository: https://packagecloud.io/AtomEditor/atom/any/ any main
        package: atom
        gpg_key_name: atom-keyring.asc
        arch: amd64
        filename: atom

    - name: Install packages dependencies
      pip:
        name: python-language-server[all]
        state: latest

    - name: install packages
      become: yes
      become_user: '{{ ansible_user_id }}'
      shell: |
        set -euo pipefail
        apm list --bare | grep -E '{{ item }}' &&
        echo 'Already installed.' ||
        apm install '{{ item }}'
      args:
        executable: /bin/bash
      loop: '{{ atom_packages | default(default_atom_packages) }}'
      register: apm_result
      changed_when: "'Already installed.' not in apm_result.stdout"
