---
- name: playbook to install awscli
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/awscli.yml

  tasks:
    - include_tasks: ../../common/install-pip-package.yml
      vars:
        package: awscli
