---
- name: playbook to install docker-compose
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/docker-compose.yml

  tasks:
    - include_tasks: debian/docker-compose-playbook.yml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - include_tasks: fedora/docker-compose-playbook.yml
      when: ansible_distribution == 'Fedora'
