---
- name: playbook to install docker
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/docker.yml

  tasks:
    - include_tasks: debian/docker-playbook.yml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - include_tasks: fedora/docker-playbook.yml
      when: ansible_distribution == 'Fedora'
