---
- name: playbook to install docker-compose
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/docker-compose.yml

  tasks:
    - name: Check current docker-compose version
      command: docker-compose --version
      register: vsn
      changed_when: false
      failed_when: false
      check_mode: no

    - set_fact:
        current_version: "{{ vsn.stdout | regex_search('(\\d+(\\.\\d+)+)') }}"
      when:
        - vsn.stdout is defined

    - name: Get latest version
      uri:
        url: https://api.github.com/repos/docker/compose/releases/latest
        method: GET
        return_content: yes
        status_code: 200
        body_format: json
      register: result

    - set_fact:
        latest_version: "{{ result.json.name | regex_search('(\\d+(\\.\\d+)+)') }}"
      when:
        - result.json is defined

    - name: Install or upgrade docker-compose
      become: yes
      get_url:
        url : '{{ github_url }}v{{ latest_version }}/docker-compose-{{ platform }}'
        dest: /usr/local/bin/docker-compose
        mode: 'a+x'
        force: yes
      when: >
        current_version is not defined
        or current_version is version(latest_version, '<')
