---
- name: playbook to install forticlient
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/forticlient.yml

  tasks:
    - name: Installing vpn package
      become: true
      apt:
        name: openfortivpn
        state: latest

    - name: Making sure vpn config directory exists
      become: true
      file:
        path: "/etc/openfortivpn"
        state: directory

    - name: Installing configuration files
      become: true
      template:
        src: "../templates/forticlient.conf"
        dest: "/etc/openfortivpn/loft.conf"
        owner: "root"
        group: "root"
        mode: 0600
      when:
        - ansible_fortihost is defined
        - ansible_forticert is defined

    - name: Configuring cron to reconnect VPN in cases where it disconnects
      become: true
      cron:
        job: "{{ ansible_user_dir }}/.local/bin/__vpn_up"
        minute: "*/15"
        name: "reconnect vpn"
        state: present
        user: root
      when:
        - with_cron
        - ansible_fortihost is defined
        - ansible_forticert is defined
