---
- name: playbook to install gcp
  hosts: localhost
  connection: local

  tasks:
    - name: Install pre-requirements
      become: true
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg
        state: latest
        update_cache: no

    - include_tasks: ../common/install-package-from-third-party.yml
      vars:
        package: google-cloud-cli
        gpg_key: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        repository_url: https://packages.cloud.google.com/apt
        suites: cloud-sdk
        components: main
