---
- name: playbook to install git
  hosts: localhost
  connection: local

  tasks:
    - name: Install git
      become: true
      apt:
        name: git
        state: latest
        update_cache: no

    - name: Install git crypt
      become: true
      apt:
        name: git-crypt
        state: latest
        update_cache: no
