---
- name: playbook to configure gnome
  hosts: localhost
  connection: local

  tasks:
    - set_fact:
        desktop_env: "{{ lookup('env', 'XDG_CURRENT_DESKTOP').split(':')[1] | lower }}"

    - name: Install gnome-tweaks
      become: true
      apt:
        name: gnome-tweaks
        state: latest
        update_cache: no
      when:
        - desktop_env in 'gnome'

    - name: Update workspace to work in all monitors
      shell: gsettings set org.gnome.mutter workspaces-only-on-primary false
      when:
        - desktop_env in 'gnome'
