---
- name: playbook to install Google Chrome
  hosts: localhost
  connection: local

  tasks:
    - include_tasks: ../common/install-package-from-third-party.yml
      vars:
        package: google-chrome-stable
        gpg_key: https://dl.google.com/linux/linux_signing_key.pub
        repository_url: http://dl.google.com/linux/chrome/deb/
        suites: stable
        components: main
