---
- name: playbook to install JOSM
  hosts: localhost
  connection: local

  tasks:
    - include_tasks: ../common/install-package-from-third-party.yml
      vars:
        package: josm
        gpg_key: https://josm.openstreetmap.de/josm-apt.key
        repository_url: https://josm.openstreetmap.de/apt
        suites: alldist
        components: universe
        arch: amd64
