---
- name: playbook to install KeePassXC
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/keepassxc.yml

  tasks:
    - name: Check current version
      command: keepassxc --version
      register: vsn
      changed_when: false
      failed_when: false
      check_mode: no

    - set_fact:
        current_version: "{{ vsn.stdout | regex_search('(\\d+(\\.\\d+)+)') }}"
      when:
        - vsn.stdout is defined

    - name: Get latest version
      uri:
        url: https://api.github.com/repos/keepassxreboot/keepassxc/releases/latest
        method: GET
        return_content: yes
        status_code: 200
        body_format: json
      register: result

    - set_fact:
        latest_version: "{{ result.json.name | regex_search('(\\d+(\\.\\d+)+)') }}"
      when:
        - result.json is defined

    - name: Install or upgrade KeePassXC
      become: yes
      get_url:
        url : '{{ github_url }}/{{ latest_version }}/KeePassXC-{{ latest_version }}-{{ platform }}.AppImage'
        dest: /usr/local/bin/keepassxc
        mode: 'a+x'
        force: yes
      when: >
        current_version is not defined
        or current_version is version(latest_version, '<')

    - name: Add Syncthing GPG Key
      become: yes
      apt_key:
        url: '{{ gpg_key }}'
        state: present

    - name: Add Syncthing Repository
      become: yes
      apt_repository:
        repo: '{{ repository }}'
        state: present
        update_cache: yes

    - name: Update apt and install Syncthing
      become: yes
      apt:
        name: syncthing
        state: latest
        update_cache: no
