---
- name: playbook to install KeePassXC
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/keepassxc.yml

  tasks:
    - name: Install keepassxc
      become: true
      apt:
        name: keepassxc
        state: latest
        update_cache: no

    - include_tasks: ../common/install-package-from-third-party.yml
      vars:
        repository: '{{ sync_repository }}'
        package: syncthing
        gpg_key_name: syncthing-archive-keyring.gpg

    - name: Create fi not exists autostart folder
      file:
        path: /home/{{ ansible_user_id }}/.config/autostart
        state: directory

    - name: Add to startup
      copy:
        src: /usr/share/applications/syncthing-start.desktop
        dest: /home/{{ ansible_user_id }}/.config/autostart/syncthing-start.desktop
