---
- name: playbook to install ngrok
  hosts: localhost
  connection: local

  tasks:
    - include_tasks: ../common/install-package-from-third-party.yml
      vars:
        gpg_key: https://ngrok-agent.s3.amazonaws.com/ngrok.asc
        gpg_key_name: ngrok.asc
        package: ngrok
        repository: "https://ngrok-agent.s3.amazonaws.com buster main"
