---
- name: playbook to install ngrok
  hosts: localhost
  connection: local

  tasks:
    - include_tasks: ../common/install-package-from-third-party.yml
      vars:
        package: ngrok
        gpg_key: https://ngrok-agent.s3.amazonaws.com/ngrok.asc
        repository_url: https://ngrok-agent.s3.amazonaws.com
        suites: buster
        components: main
