---
- name: playbook to install protonvpn
  hosts: localhost
  connection: local

  tasks:
    - name: Install systemd-timesyncd
      become: true
      apt:
        name: systemd-timesyncd
        state: latest
        update_cache: false
      notify: enable_prometheus

    - name: Install node_exporter
      become: true
      apt:
        name: prometheus-node-exporter
        state: latest
        update_cache: false
      notify: enable_prometheus

    - name: Set ip if defined
      set_fact:
        ip: '{{ host_ip }}'
      when: host_ip is defined

    - name: Set ip if not defined
      set_fact:
        ip: '{{ inventory_hostname }}'
      when: host_ip is not defined

    - name: Bind prometheus-node-exporter to local IP
      become: true
      replace:
        path: /etc/default/prometheus-node-exporter
        regexp: 'ARGS=""'
        replace: 'ARGS="--web.listen-address={{ ip }}:9100"'
      notify: enable_prometheus

    - name: Add sleep before prometheus-node-exporter startup
      become: true
      replace:
        path: /lib/systemd/system/prometheus-node-exporter.service
        regexp: 'EnvironmentFile=/etc/default/prometheus-node-exporter\nExecStart=/usr/bin/prometheus-node-exporter \$ARGS'
        replace: 'EnvironmentFile=/etc/default/prometheus-node-exporter\nExecStartPre=sleep 60\nExecStart=/usr/bin/prometheus-node-exporter $ARGS'
      notify:
        - enable_prometheus
        - reload_systemd

    - name: Get all systemctl services
      systemd_service:
        name: firewalld
      register: firewall_status

    - name: Get firewall open ports if running
      become: true
      shell: firewall-cmd --list-ports
      register: opened_ports
      failed_when: false

    - name: Enable node-exporter port if firewall running
      become: true
      shell: firewall-cmd --permanent --zone=public --add-port=9100/tcp
      when: |
        firewall_status.status.ActiveState == "active" and
        "9100/tcp" not in opened_ports.stdout
      notify: open_firewall_port

  handlers:
    - name: Enable prometheus-node-exporter
      become: true
      systemd_service:
        name: prometheus-node-exporter
        enabled: true
        state: restarted
      listen: enable_prometheus

    - name: Reload systemctl daemon
      become: true
      systemd_service:
        daemon_reload: true
      listen: reload_systemd

    - name: Enable prometheus-node-exporter
      become: true
      systemd_service:
        name: firewalld
        enabled: true
        state: restarted
      listen: open_firewall_port