---
- name: playbook to install nodejs
  hosts: localhost
  connection: local

  tasks:
    - name: Install requirements
      become: yes
      become_user: root
      apt:
        name:
          - apt-transport-https
          - lsb-release
          - curl
          - gnupg
        state: latest
        update_cache: no

    - name: Download node install script
      get_url:
        url: https://deb.nodesource.com/setup_current.x
        dest: /tmp
        mode: 'u=rw,go=r'

    - name: Execute script
      become: yes
      become_user: root
      shell: bash /tmp/setup_current.x

    - name: Install nodejs and npm
      become: yes
      become_user: root
      apt:
        name:
          - nodejs
        state: latest
        update_cache: no
