---
- name: playbook to install signal
  hosts: localhost
  connection: local

  tasks:
    - include_tasks: ../common/install-package-from-third-party.yml
      vars:
        package: signal-desktop
        gpg_key: https://updates.signal.org/desktop/apt/keys.asc
        repository_url: https://updates.signal.org/desktop/apt
        suites: xenial
        components: main
