---
- name: playbook to install steam installer
  hosts: localhost
  connection: local

  tasks:
    - name: Install Steam installer
      become: yes
      apt:
        deb: https://cdn.cloudflare.steamstatic.com/client/installer/steam.deb
        update_cache: yes
        install_recommends: yes
