---
- name: playbook to install steam installer
  hosts: localhost
  connection: local

  tasks:
    - name: Install dependencies
      become: true
      apt:
        name:
          - software-properties-common
          - apt-transport-https
          - dirmngr
          - ca-certificates
          - curl
        update_cache: no
        state: latest

    - name: Install Steam
      become: true
      apt:
        name: 
          - steam-installer
          - steam-devices
        update_cache: yes
        state: latest
