---
- name: playbook to install terraform
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/terraform.yml

  tasks:
    - include_tasks: ../common/install-package-from-third-party.yml
      vars:
        gpg_key: https://apt.releases.hashicorp.com/gpg
        package: terraform
        repository_url: https://apt.releases.hashicorp.com
        suites: buster
        components: main
