---
- name: playbook to install vlc
  hosts: localhost
  connection: local

  tasks:
    - name: Install latest version of vlc
      become: true
      apt:
        name: vlc
        state: latest
        update_cache: no
