---
- name: playbook to install VSCodium
  hosts: localhost
  connection: local

  tasks:
    - include_tasks: ../common/install-package-from-third-party.yml
      vars:
        package: codium
        gpg_key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
        repository_url: https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs
        suites: vscodium
        components: main

