---
- name: playbook to install zoom
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/zoom.yml

  tasks:
    - name: Install latest version of zoom with dependencies
      become: yes
      become_user: root
      apt:
        deb: "{{ zoom_url }}"
        state: present
        update_cache: no
