---
- name: playbook to install zoom
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/zoom.yml

  tasks:
    - name: Install required pakcages
      become: yes
      apt:
        name:
          - libglib2.0-0
          - libgstreamer-plugins-base1.0-0
          - libxcb-shape0
          - libxcb-shm0
          - libxcb-xfixes0
          - libxcb-randr0
          - libxcb-image0
          - libfontconfig1
          - libgl1-mesa-glx
          - libxi6
          - libsm6
          - libxrender1
          - libpulse0
          - libxcomposite1
          - libxslt1.1
          - libsqlite3-0
          - libxcb-keysyms1
          - libxcb-xtest0
          - libxkbcommon-x11-0
        state: latest
        update_cache: no

    - name: Download zoom
      become: yes
      get_url:
        url: '{{ zoom_url }}'
        dest: '{{ zoom_deb_dest }}'

    - name: Check zoom downloaded version
      become: yes
      command: 'dpkg --info {{ zoom_deb_path }}'
      register: zoom_check_deb_version
      failed_when: false
      changed_when: false

    - set_fact:
        zoom_deb_version: "{{ zoom_check_deb_version.stdout | regex_search('(Version: \\d+(\\.\\d+)+)') }}"
      when:
        - zoom_check_deb_version.sdtout is defined

    - name: Check installed zoom version
      become: yes
      command: dpkg -s zoom
      register: zoom_check_installed_version
      failed_when: false
      changed_when: false

    - set_fact:
        zoom_installed_version: "{{ zoom_check_installed_version.stdout | regex_search('(Version: \\d+(\\.\\d+)+)') }}"
      when:
        - zoom_check_installed_version.sdtout is defined

    - name: Install zoom
      become: yes
      apt:
        deb: '{{ zoom_deb_path }}'
      when: >
        zoom_installed_version is not defined
        or zoom_installed_version is version(zoom_deb_version, '!=')
